apiVersion: v1
kind: Service
metadata:
  name: techmarket-service
  namespace: techmarket
spec:
  type: LoadBalancer
  selector:
    app: techmarket-orders
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
