name: Reusable Deploy

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      eks_cluster:
        required: true
        type: string
      namespace:
        required: true
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.aws_region }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region ${{ inputs.aws_region }} \
            --name ${{ inputs.eks_cluster }}

      - name: Create Namespace
        run: |
          kubectl apply -f k8s/base/namespace.yaml

      - name: Wait Namespace
        run: sleep 5

      - name: Deploy ConfigMap
        run: |
          kubectl apply -f k8s/base/configmap.yaml

      - name: Deploy Service
        run: |
          kubectl apply -f k8s/base/service.yaml

      - name: Deploy Blue
        run: |
          kubectl apply -f k8s/blue/

      - name: Deploy Green
        run: |
          kubectl apply -f k8s/green/

      - name: Health Check
        run: |
          kubectl rollout status deployment/techmarket-green \
            -n ${{ inputs.namespace }} \
            --timeout=180s

      - name: Switch Traffic
        run: |
          kubectl patch service techmarket-service \
            -n ${{ inputs.namespace }} \
            -p '{"spec":{"selector":{"app":"techmarket-orders","version":"green"}}}'

      - name: Rollback
        if: failure()
        run: |
          kubectl patch service techmarket-service \
            -n ${{ inputs.namespace }} \
            -p '{"spec":{"selector":{"app":"techmarket-orders","version":"blue"}}}'
